version: '2.2'

networks:
  default:
    external:
      name: cyber-dojo

services:

  runner_repl:
    build:
      context: server
      args:
         - CYBER_DOJO_RUNNER_HOME=/app
         - PORT=4657
    user: root
    image: cyberdojo/runner_repl
    init: true
    container_name: test_runner_repl_server
    read_only: false
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    ports:
      - 4657:4657
