
version: '2.2'

services:

  # runner_processful_client:
  #   build:
  #     context: client
  #     args:
  #       - CYBER_DOJO_RUNNER_HOME=${CYBER_DOJO_RUNNER_HOME}
  #       - PORT=${CYBER_DOJO_RUNNER_CLIENT_PORT}
  #   user: nobody
  #   image: cyberdojo/runner_processful_client
  #   init: true
  #   container_name: test_runner_processful_client
  #   read_only: true
  #   tmpfs: /tmp
  #   restart: 'no'
  #   depends_on:
  #     - runner_processful
  #   environment:
  #     - CYBER_DOJO_RUNNER_SERVICE_NAME
  #     - CYBER_DOJO_RUNNER_SERVICE_PORT
  #     - CYBER_DOJO_COVERAGE_ROOT
  #   ports:
  #     - ${CYBER_DOJO_RUNNER_CLIENT_PORT}:${CYBER_DOJO_RUNNER_CLIENT_PORT}

  # - - - - - - - - - - - - - - - - - - - - - - - - - -

  runner_repl:
    build:
      context: server
      args:
        - CYBER_DOJO_RUNNER_HOME=${CYBER_DOJO_RUNNER_HOME}
        - PORT=${CYBER_DOJO_RUNNER_SERVICE_PORT}
    user: root
    image: cyberdojo/runner_repl
    init: true
    container_name: test_runner_repl_server
    read_only: false
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    ports:
      - ${CYBER_DOJO_RUNNER_SERVICE_PORT}:${CYBER_DOJO_RUNNER_SERVICE_PORT}
